# Netlify Configuration
[build]
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "https://auraquant-api-prod.onrender.com/api/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
