services:
  # Backend API Service
  - type: web
    name: auraquant-live-api
    runtime: python
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements-minimal.txt
    startCommand: python main.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: WEBHOOK_SECRET_TOKEN
        generateValue: true
      # Add your API keys from Render dashboard
      # Do not commit actual API keys to git
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_SECRET_KEY
        sync: false
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
    region: oregon # Change to your preferred region
