# Cloudflare Pages Configuration for AuraQuant Frontend
name = "auraquant-frontend"
compatibility_date = "2024-01-01"

[site]
bucket = "./"

[vars]
API_URL = "https://auraquant-api-prod.onrender.com"
WS_URL = "wss://auraquant-api-prod.onrender.com"
ENVIRONMENT = "production"
