services:
  - type: web
    name: auraquant-backend
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements-minimal.txt"
    startCommand: "python main.py"
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
